/** @format */

export const Consultation_List = [
  {
    category: "Health and fitness",
    course_title: "How to make ayour first million as a front-end developer",
    price: 50.99,
    discount_price: 30.99,
    courseRating: 4.9,
    no_of_reviews: 3500,
    students: 70050,
    sessions: 5,
    time: 5,
    author: "Joseph Sam"
  },
  {
    category: "commentary",
    course_title: "Learn everthing you need to know about self growth",
    price: 20.99,
    discount_price: 15.99,
    courseRating: 3.9,
    no_of_reviews: 100,
    students: 1000,
    sessions: 7,
    time: 9,
    author: "Andrew Williams",
  },
  {
    category: "SEO Marketing",
    course_title: "Learn SEO Analytics",
    price: 75.99,
    discount_price: 50.99,
    courseRating: 4.4,
    no_of_reviews: 2450,
    students: 1050,
    sessions: 4,
    time: 3,
    author: "Kyle Walker",
  },
  {
    category: "Data Analysis",
    course_title: "How to make ayour first million as a Data Analyst",
    price: 100.99,
    discount_price: 75.99,
    courseRating: 5.0,
    no_of_reviews: 3500,
    students: 750,
    sessions: 15,
    time: 20,
    author: "James Brown",
  },
  {
    category: "Computing",
    course_title: "Machine learning and robotics",
    price: 175.0,
    discount_price: 120.99,
    courseRating: 4.7,
    no_of_reviews: 7500,
    students: 108900,
    sessions: 11,
    time: 9,
    author: "John Smith",
  },
  {
    category: "Networking",
    course_title: "Make more connections to your future",
    price: 15.99,
    discount_price: 10.99,
    courseRating: 5.0,
    no_of_reviews: 600,
    students: 4050,
    sessions: 16,
    time: 16,
    author: "Paul Gilbert",
  },
];
